In [1]:
import numpy as np


In [2]:
data  = np.arange(24).reshape(2,3,4)

In [3]:
data

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
data[1,0:2,3:]

array([[15],
       [19]])

In [15]:
data[:,2:4,:]

array([[[ 8,  9, 10, 11]],

       [[20, 21, 22, 23]]])

In [23]:
data[1,:,0:3]

array([[12, 13, 14],
       [16, 17, 18],
       [20, 21, 22]])

In [29]:
data[1,0::2,0:3:2]

array([[12, 14],
       [20, 22]])

In [32]:
arr4 = np.arange(100).reshape(4,5,5)

In [35]:
arr4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [36]:
arr4[2:,:,:]

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [44]:
arr4[3:,1:3,3:]

array([[[83, 84],
        [88, 89]]])

NameError: name 'array' is not defined