In [1]:
import numpy as np

In [2]:
# numpy ma be indexing same ase he ho ge jaisa list ma hotii the 0 sa start

In [3]:
# start end step ya 3 no slicing ma hoty han

In [4]:
# slicong 0 sa start hotii han postive sa tu or negative sa -1 sa start hoti han

In [9]:
x = np.array([1,2,7,9,5,6])

In [10]:
x[4]

5

In [11]:
x>5

array([False, False,  True,  True, False,  True])

In [12]:
x[x>5]

array([7, 9, 6])

# fancy indexing

In [15]:
x[[1,2,5]] # ya iskae andr jitnay be pass karay han wo index pass karay han ya index kii value lay kar a raha han

array([2, 7, 6])

In [17]:
x[1,2] #agar asa pas ar raha ho a=error a raha han or yahe kaam fancy indexing sa karo ga tu 4n ho ja ga

IndexError: too many indices for array

In [18]:
x = np.random.randn(10,10)

In [19]:
x

array([[-0.46512157, -0.38952353,  0.50226657, -0.74182008,  1.30344875,
        -0.0182161 ,  0.3055409 ,  0.60876867,  0.52734617, -0.09250395],
       [ 1.49424997, -1.64379346,  0.67843821,  0.3497375 , -0.91985566,
         1.57034697,  0.35266512,  0.18775711,  0.4295902 ,  1.91083333],
       [-1.53530542,  1.11950399, -0.08930885,  0.2003807 , -0.00531852,
        -0.33962006, -1.17661868,  1.24879364, -0.0568625 ,  0.6175858 ],
       [ 0.42254107, -0.29827044,  0.52701763, -1.49429383,  0.19607817,
        -0.07836426,  0.24751847, -0.58109373,  0.8044925 ,  0.88357978],
       [-1.08418968,  2.18428285, -2.03256513,  1.41148828,  0.89860195,
        -0.44494486, -0.73762829,  0.27566847,  0.50819057, -0.59761385],
       [-1.18095622,  1.70687484, -1.01858322,  0.57171936,  0.30432911,
         0.17445684, -0.27413717,  0.85724039, -0.88612468,  0.65783879],
       [ 0.6053738 ,  0.51193411,  1.78629364, -1.68054222,  0.68209503,
         0.19579164, -0.917402  ,  0.27026965

In [20]:
x[0]

array([-0.46512157, -0.38952353,  0.50226657, -0.74182008,  1.30344875,
       -0.0182161 ,  0.3055409 ,  0.60876867,  0.52734617, -0.09250395])

In [23]:
x[9]

array([ 1.03291014, -1.46494237, -0.97853767,  0.91187196,  0.56197157,
       -0.52224011,  0.02887578,  2.31600172,  0.00791171, -0.96045816])

In [24]:
# ab ma chata ho 1 row ka 5 column a jay

In [27]:
x[0][4]

1.3034487453274397

In [33]:
x[0:10:2,::] # ya jo 0 sa start kara han starting value han or jo end han wo 10 han or 2 jo han wo step han or , kaha tak chahiye pora tu :: laga dayna han

array([[-0.46512157, -0.38952353,  0.50226657, -0.74182008,  1.30344875,
        -0.0182161 ,  0.3055409 ,  0.60876867,  0.52734617, -0.09250395],
       [-1.53530542,  1.11950399, -0.08930885,  0.2003807 , -0.00531852,
        -0.33962006, -1.17661868,  1.24879364, -0.0568625 ,  0.6175858 ],
       [-1.08418968,  2.18428285, -2.03256513,  1.41148828,  0.89860195,
        -0.44494486, -0.73762829,  0.27566847,  0.50819057, -0.59761385],
       [ 0.6053738 ,  0.51193411,  1.78629364, -1.68054222,  0.68209503,
         0.19579164, -0.917402  ,  0.27026965,  0.21894474,  1.02983385],
       [ 0.49029058,  1.63391526, -1.24080459,  0.68444398,  2.04412775,
         0.71433976,  0.6139547 , -0.3268507 ,  0.33204369, -1.39863413]])

In [42]:
x[::,0:5]

array([[-0.46512157, -0.38952353,  0.50226657, -0.74182008,  1.30344875],
       [ 1.49424997, -1.64379346,  0.67843821,  0.3497375 , -0.91985566],
       [-1.53530542,  1.11950399, -0.08930885,  0.2003807 , -0.00531852],
       [ 0.42254107, -0.29827044,  0.52701763, -1.49429383,  0.19607817],
       [-1.08418968,  2.18428285, -2.03256513,  1.41148828,  0.89860195],
       [-1.18095622,  1.70687484, -1.01858322,  0.57171936,  0.30432911],
       [ 0.6053738 ,  0.51193411,  1.78629364, -1.68054222,  0.68209503],
       [ 0.11690937, -0.86588429,  0.10575294,  2.0047939 , -0.27677158],
       [ 0.49029058,  1.63391526, -1.24080459,  0.68444398,  2.04412775],
       [ 1.03291014, -1.46494237, -0.97853767,  0.91187196,  0.56197157]])

In [169]:
x = np.ones((5,5))

In [133]:
x

array([[2., 2., 2., 2., 5.],
       [2., 2., 2., 2., 5.],
       [2., 2., 2., 2., 5.],
       [2., 2., 2., 2., 5.],
       [2., 2., 2., 2., 5.]])

In [56]:
x[1:-1,1:-1] # 1 jo mtlb phlii row : -1 phir akhrii row phir , 1 column phir : -1 akhrii column

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [117]:
x[1:-101:-1] = 0
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [96]:
x[0:5,0:5] = 1

In [167]:
x[0:5,-1:] = 5

In [168]:
x

array([[2., 2., 2., 2., 5.],
       [2., 2., 2., 2., 5.],
       [2., 2., 2., 2., 5.],
       [2., 2., 2., 2., 5.],
       [0., 2., 2., 2., 5.]])

In [161]:
x[0:5,1:5] = 0

In [162]:
x

array([[2., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [165]:
x[0:5,1:5] = 2

In [166]:
x

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [0., 2., 2., 2., 2.]])

In [170]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [173]:
x[2:5,1:4]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [186]:
x[1:5,1:-1] = 1

In [187]:
x

array([[1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
array = 