In [1]:
import numpy as np

# 1 D Array

In [2]:
#create 1D Array
d = np.array([3,2,1,4,5])
#             0,1,2,3,4


In [3]:
d

array([3, 2, 1, 4, 5])

In [4]:
#Indexing  in 1D Array

In [5]:
# accsing element with indexing

In [6]:
d[4]# 4 index par 5

5

In [7]:
d[3]# 3 index par 4

4

# Slicing 1D Array

In [8]:
#arrayName [startIndex : Ending Index+1] Ending Index Not include

In [9]:
d[0:2]

array([3, 2])

In [10]:
d[0:4] #4 index han tu 3 tak chlay ga

array([3, 2, 1, 4])

# 2D Array

#2D Array is just Like The Simple Martix

In [11]:
array_2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
# A Martix of 3 rows 3 column
array_2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Indexing in 2D Array 

In [12]:
# Indexing In 2D Arrays
#arrayName [row number][element number]

In [13]:
print("   0 Row 4 index element      ")
array_2D[0][3] # ya dekhyn 0 row par 3ra index print karo


   0 Row 4 index element      


4

In [14]:
print("   1 Row 2ra index            ")
array_2D[1][2]

   1 Row 2ra index            


8

# Slicing in 2D Array

1.Access Elements in 2D Array

2.Aceess Specific row and Specific column 

In [15]:
array_2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
# Print Specific Element
array_2D[1,1] # first row(row start with 0 index) second index element

7

In [17]:
array_2D[0,3]# 0 row (row start with 0 index) then 3 element of index

4

#Access Specific row or specific column

In [18]:
for i in array_2D:
    print(i)


[1 2 3 4 5]
[ 6  7  8  9 10]


In [19]:
print(array_2D[0])
print(array_2D[1])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [20]:
# Case : 1 : We Have print to print 2nd Column
# Arrayname ; [row:column]
array_2D[:,2] # start : mtlb all row select ab , kae baad konsa column 2 wala tu ya column kii indexing  0 sa start hotii han

array([3, 8])

In [21]:
array_2D[: , 2]

array([3, 8])

# 3D Array

In [22]:
string = np.array(["Sas","khan"])

In [23]:
type(string)

numpy.ndarray

In [24]:
string

array(['Sas', 'khan'], dtype='<U4')

In [25]:
# Create 3D Array
array_3D = np.array([[[1,2,3] , [4,5,6] , [7,8,9]] ,
                    [[10,11,12] , [13,14,15] , [16,17,18]],
                    [[19,20,21] , [22,23,24] , [25,26,27] , [28,29,30]]])


In [26]:
array_3D

array([list([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
       list([[10, 11, 12], [13, 14, 15], [16, 17, 18]]),
       list([[19, 20, 21], [22, 23, 24], [25, 26, 27], [28, 29, 30]])],
      dtype=object)

# indexing in 3D Array

In [27]:
rnd = np.random.randn(5,5)

In [28]:

# create 3D Array
array_3D = np.array([[[1,2,3] , [4, 5 , 6] , [7, 8, 9]] ,
                     [[10 ,11, 12] , [13, 14, 15] , [16 , 17 ,18]], 
                     [[19,20,21] , [22,23,24] , [25,26,27]]])
array_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [29]:
# Case 1: we have to print 5 from first set
array_3D[0,1,1] #is ma 0 jo han wo index han or 1 jo han wo 0 index ka cloumn no 1 han or uskae baad wala number column ka index 1

5

In [30]:
# Case 2: we have print the 2nd column of the second martix
array_3D[1,:,1]

array([11, 14, 17])

In [31]:
array_3D[1,1,1]

14

In [32]:
array_3D[2]

array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [33]:
array_3D[2,2,2]

27

In [34]:
array_3D[2,1:,1:]

array([[23, 24],
       [26, 27]])

In [35]:
arr2d= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
arr2d[1:,0:2]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [37]:
arr2d[1][0]

4

In [38]:
data = {i : np.random.randn() for i in range(7)}

In [39]:
data

{0: -1.3145438636678886,
 1: -0.5456815855607288,
 2: -0.44019610856125274,
 3: -0.07943094127182834,
 4: 1.7842521951599093,
 5: -0.07104622907353324,
 6: -1.9556914569254116}

In [40]:
array2d = np.array([[45,24,65],[65,3564,46],[45,56,5]])

In [41]:
array2d

array([[  45,   24,   65],
       [  65, 3564,   46],
       [  45,   56,    5]])

In [42]:
array2d[0]

array([45, 24, 65])

In [43]:
array2d[1]

array([  65, 3564,   46])

In [44]:
array2d[2]

array([45, 56,  5])

In [45]:
array2d[1,1]

3564

In [46]:
array2d[:2,1:]

array([[  24,   65],
       [3564,   46]])

In [47]:
array3d = np.array([[[100,200,300],[400,500,600],[700,800,900]],[[1,2,3],[4,5,6],[7,8,9]]])

In [48]:
array3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]],

       [[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]])

In [49]:
array3d.shape

(2, 3, 3)

In [52]:
array3d.ndim #  ya ndim mtlb shape jaisa bata han kae ya kitnay size kii dimenstioon han wase ya be dimention bata han kitay size kii dimention han

3

In [51]:
np.empty((2,3,3))

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [6.39744384e-308, 5.56294608e-307, 2.44770517e-307],
        [1.11256817e-306, 1.06811422e-306, 1.42417221e-306]],

       [[1.11260619e-306, 8.90094053e-307, 1.86919378e-306],
        [1.06809792e-306, 1.37962456e-306, 1.69111861e-306],
        [1.78020169e-306, 1.37961777e-306, 7.56599807e-307]]])

In [56]:
np.ones_like()

array(1)

In [57]:
array3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]],

       [[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]])

In [58]:
array3d[1,1,0]

4

In [59]:
array3d[1,1,:]

array([4, 5, 6])

In [62]:
array3d[0,0:2,1:]

array([[200, 300],
       [500, 600]])

In [65]:
ar = np.arange(1,37).reshape(6,6)

In [66]:
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [67]:
#[row,column]

In [70]:
ar[:,2]

array([ 3,  9, 15, 21, 27, 33])

In [75]:
ar[1:4,3:]

array([[10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])

In [76]:
ar[2:4,5:]

array([[18],
       [24]])

# Boolean Indexing

In [78]:
data = np.random.randn(7,4)

In [79]:
data

array([[-0.50346856,  0.094093  ,  0.32062838, -0.34281379],
       [ 0.9038069 ,  1.81941914,  0.16467825, -0.54518687],
       [ 0.70970277,  0.46383021,  0.16725206, -2.05557268],
       [ 0.506854  ,  2.56338803, -1.25037228,  2.52614419],
       [-1.02041455,  0.32728304,  0.14999157, -0.02349899],
       [ 0.74850781,  0.03288342, -0.33374371, -0.95750817],
       [ 0.36605488, -0.56196322, -1.4100866 ,  0.30920744]])

In [80]:
bol = np.array([True,False,False,False,False,True,False],dtype="bool")

In [81]:
data[bol]

array([[-0.50346856,  0.094093  ,  0.32062838, -0.34281379],
       [ 0.74850781,  0.03288342, -0.33374371, -0.95750817]])

In [82]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [85]:
names != 'Bob' # jaha jaha ya Bob nhi waha true kar deya jaha tha waha  false kardiya

array([False,  True,  True, False,  True,  True,  True])

In [86]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [88]:
data[names != 'Bob']

array([[ 0.9038069 ,  1.81941914,  0.16467825, -0.54518687],
       [ 0.70970277,  0.46383021,  0.16725206, -2.05557268],
       [-1.02041455,  0.32728304,  0.14999157, -0.02349899],
       [ 0.74850781,  0.03288342, -0.33374371, -0.95750817],
       [ 0.36605488, -0.56196322, -1.4100866 ,  0.30920744]])

In [89]:
cond = names != 'Bob'

In [90]:
cond

array([False,  True,  True, False,  True,  True,  True])

In [92]:
data[cond]

array([[ 0.9038069 ,  1.81941914,  0.16467825, -0.54518687],
       [ 0.70970277,  0.46383021,  0.16725206, -2.05557268],
       [-1.02041455,  0.32728304,  0.14999157, -0.02349899],
       [ 0.74850781,  0.03288342, -0.33374371, -0.95750817],
       [ 0.36605488, -0.56196322, -1.4100866 ,  0.30920744]])

In [93]:
data[~cond] # "~" negation ka sign ture hoge tu false karday ga or false ho ge tu true kar day ga jaisa python ma "not" karta tha

array([[-0.50346856,  0.094093  ,  0.32062838, -0.34281379],
       [ 0.506854  ,  2.56338803, -1.25037228,  2.52614419]])

In [94]:
data

array([[-0.50346856,  0.094093  ,  0.32062838, -0.34281379],
       [ 0.9038069 ,  1.81941914,  0.16467825, -0.54518687],
       [ 0.70970277,  0.46383021,  0.16725206, -2.05557268],
       [ 0.506854  ,  2.56338803, -1.25037228,  2.52614419],
       [-1.02041455,  0.32728304,  0.14999157, -0.02349899],
       [ 0.74850781,  0.03288342, -0.33374371, -0.95750817],
       [ 0.36605488, -0.56196322, -1.4100866 ,  0.30920744]])