In [1]:
import numpy as np

# dot() # do martix multiply karni han tu wo dot kae function sa multiply ho ge

In [2]:
Row = int(input("Enter The Row :"))
Column = int(input("Enter The Column :"))

sa = np.random.randn(Row,Column)

print(sa)

Enter The Row :3
Enter The Column :2
[[ 0.31154282  0.07050254]
 [-1.39391456 -0.05330874]
 [ 2.08986783  0.53021285]]


In [7]:
x = np.random.randn(3,2)
x

array([[ 0.18301497,  0.11354207],
       [ 0.18031381, -0.96473535],
       [ 0.81187005, -0.38142908]])

In [8]:
y = np.random.randn(2,3)
y

array([[ 0.45822935, -0.12846565, -1.0650223 ],
       [-0.01767555, -0.65742706, -1.16169365]])

In [5]:
x.dot(y)

array([[-1.87706842,  0.44794687, -0.21926987],
       [-2.2236929 ,  1.00833422, -0.19933215],
       [ 2.24517373,  0.09159043,  0.3416388 ]])

In [9]:
x.transpose() # is nai convert kar deya 2 by 3 ma 

array([[ 0.18301497,  0.18031381,  0.81187005],
       [ 0.11354207, -0.96473535, -0.38142908]])