In [1]:
import numpy as np

In [3]:
np.zeros([4,4])# isay numpy kii ka array create ho ge jis kae saray element 0 ho gayn

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.empty([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
#list ko hum array hum array ma convert kar dayn gayn

In [8]:
l = [5,4,3,2,1]

In [9]:
np.array(l)

array([5, 4, 3, 2, 1])

In [11]:
print(np.arange(1,100,5))

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [14]:
x = np.arange(10)

In [16]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
s = np.zeros([10,10])

In [30]:
s.shape # ya bata deya 10 by 10 kii shape ka array han

(10, 10)

In [22]:
s = np.arange(1,100,5)

In [23]:
s.shape

(20,)

In [37]:
s.reshape((2,2,5,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])