In [1]:
import numpy as np

In [10]:
x = np.array([2,4,5,6,8,9])

In [11]:
x

array([2, 4, 5, 6, 8, 9])

In [12]:
np.sqrt(x)

array([1.41421356, 2.        , 2.23606798, 2.44948974, 2.82842712,
       3.        ])

In [13]:
np.power(x,2) # ya har element ka squre nikla han

array([ 4, 16, 25, 36, 64, 81], dtype=int32)

In [14]:
y = [3,2,4,5,6,-1]

In [15]:
np.maximum(x,y)

array([3, 4, 5, 6, 8, 9])

'55555'

# WHere 

In [7]:
Salary = np.array([0,-1,10000,22000])

In [8]:
Salary

array([    0,    -1, 10000, 22000])

In [10]:
np.where(Salary<=0,25000,Salary)# ya hum nai condition laga de kae agar salary 0 < han tu 25000 kardu

array([25000, 25000, 10000, 22000])

In [12]:
np.where(Salary<=0,"Not Ok","OKe") #  ma yaha par kuch or be likh sakta ho jaisa jaha  par salary theak de hoe han waha  par likho OK jaha galat han waha likhon NOt :Ok

array(['Not Ok', 'Not Ok', 'OKe', 'OKe'], dtype='<U6')

# Mathematical And Statistical Methods

In [14]:
x = np.array([10,9,7,10,7])

In [15]:
x

array([10,  9,  7, 10,  7])

In [16]:
x.mean()

8.6

In [19]:
x.cumsum() # cumulative Sum jo hn har agay hum ko phalay walay jtnai be number han add karta han

array([10, 19, 26, 36, 43], dtype=int32)

In [20]:
x

array([10,  9,  7, 10,  7])

In [22]:
x.cumprod() # ya har pechlay jitna be number ha sub ko multiply karta ha 

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [31]:
y = x > 6

In [32]:
y

array([ True,  True,  True,  True,  True])

In [34]:
y.sum() # ya dekhyn is nai mujha batya kae kitnai true values han is ma

5

In [36]:
y.any() # ya check karnay kae liya kae koe element true han be ya nhi

True

In [37]:
y.all()

True

In [39]:
y = x > 7

In [41]:
y

array([ True,  True, False,  True, False])

In [43]:
y.sum() # ya dekhyn batya is nai kae kitna true han ya false

3

In [45]:
y.any() # han koe be ak true han

True

In [47]:
y.all() # all ya check kar rha han kae kia tamam elements true han ya nhi

False

In [48]:
y.sort()

In [49]:
y

array([False, False,  True,  True,  True])

In [50]:
x.sort()

In [51]:
x

array([ 7,  7,  9, 10, 10])

In [57]:
np.unique(x)

array([ 7,  9, 10])