In [1]:
import numpy as np

In [3]:
l = range(1000000)

In [7]:
%time for i in range(1,10):r=[x*2 for x in l]

Wall time: 2.38 s


In [9]:
%time for i in range(1,10):r=d*2

Wall time: 108 ms


In [5]:
d = np.arange(1000000)

In [11]:
x = np.zeros((4,4))

In [12]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
s = np.ones((5,5))

In [14]:
s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.empty((7,7)) # ya kuch be value khud be output day ga randomly kuch be lay kar ay ga

array([[             nan,  6.89903272e-310,  4.01181304e-321,
         1.97626258e-323,  4.42682819e-321,  4.76223221e-287,
         4.20943930e-321],
       [ 7.93544645e-301,  3.87347466e-321,  7.93544645e-301,
         3.85371204e-321,  1.34047035e-272,  2.84581812e-321,
         1.69265300e-258],
       [ 5.43472210e-321,  1.29457963e-272,  5.45448473e-321,
         2.49612436e-306,  4.01181304e-321,  1.29620431e-272,
         5.71139887e-321],
       [ 7.53790860e-244,  5.61258574e-321, -7.31469412e-114,
         4.01181304e-321,  3.48014949e-308,  3.47748437e-308,
         4.63524825e-273],
       [ 1.32122555e-228,  1.64643684e-287,  1.29397745e-272,
         1.34065087e-272,  1.63535102e-301,  8.86040129e-220,
         1.29440476e-272],
       [ 2.78137431e-308,  1.63786265e-301,  2.04564941e-277,
         1.29405083e-272,  2.43550680e-209,  3.75833466e-308,
         4.87548614e+127],
       [ 7.26883240e-249,  1.43246684e-277,  7.26883230e-249,
         2.04512008e-277,  4.229

# Converd list To Numpy list

In [19]:
l = [1,2,3,4,5,6,7]

In [21]:
np.array(l) # this list converd in numpy array

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# another be han

In [25]:
x = np.arange(1,100,10)
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [28]:
x.shape

(10,)

In [32]:
s = np.zeros((10,10))
s

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
s.reshape((2,2,5,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

# Vertication Add Subtract anything operation

In [34]:
a = np.random.randn((10))

In [35]:
b = np.random.randn((10))

In [36]:
a

array([ 0.63445529, -0.39802062, -1.80732035, -0.46576744, -0.55451588,
       -0.02918323,  0.08468246, -0.03475528, -0.31735303, -1.05761643])

In [37]:
b

array([-0.11019138,  0.66257111,  0.27476206, -0.54303435, -1.08413669,
       -1.86587821,  0.99581367, -2.76096368,  0.74265804, -1.18459581])

In [38]:
a+b

array([ 0.52426391,  0.26455049, -1.53255829, -1.00880178, -1.63865257,
       -1.89506144,  1.08049613, -2.79571896,  0.42530502, -2.24221225])

In [39]:
a-b

array([ 0.74464667, -1.06059173, -2.08208242,  0.07726691,  0.52962081,
        1.83669498, -0.91113121,  2.7262084 , -1.06001107,  0.12697938])

In [40]:
a*b

array([-0.0699115 , -0.26371696, -0.49658307,  0.25292772,  0.60117101,
        0.05445235,  0.08432795,  0.09595806, -0.23568478,  1.252848  ])

In [41]:
2*a

array([ 1.26891058, -0.79604123, -3.61464071, -0.93153487, -1.10903176,
       -0.05836646,  0.16936492, -0.06951056, -0.63470605, -2.11523287])

In [42]:
a>0

array([ True, False, False, False, False, False,  True, False, False,
       False])

In [43]:
# ab yahe mujha element dekhynai han kae konsi value han jo barii han

In [45]:
a[a>0]

array([0.63445529, 0.08468246])

# Indexing and Slicing

In [46]:
b = np.array([1,2,4,5,8,6])

In [48]:
b[4] # ya index kii value check kare han

8

In [51]:
b > 5 # jaha jaha 5 say bara han waha  ture ha baqii sub false han

array([False, False, False, False,  True,  True])

In [54]:
b[[2,1]] # this are fancy indexing list pass kare or jaha wo values han wo number a rahay hayn

array([4, 2])

# slicing 

In [55]:
s = np.random.randn(10,10)

In [56]:
s

array([[-1.97463137e-01, -5.48454152e-01, -2.80812292e-03,
        -1.80277411e+00,  1.04389841e-01, -1.00140810e+00,
        -3.44047733e-01,  1.59430576e-02,  7.24247074e-01,
         1.09418171e+00],
       [ 8.02585426e-01, -1.35283220e+00,  6.99936356e-01,
         2.11413109e+00, -5.83607035e-01, -7.11109924e-01,
         4.33078323e-01, -8.64582927e-01,  1.48840956e-04,
        -2.49997164e+00],
       [-7.18204262e-01,  8.60414419e-01, -6.20130969e-01,
         1.29363055e+00,  4.40725117e-01, -8.11663977e-01,
         3.92290285e-01,  9.96921702e-01,  5.63553116e-01,
         5.11864802e-01],
       [ 5.15948230e-01, -1.78815028e+00,  1.11027204e+00,
        -2.02900696e+00,  1.94846028e+00, -6.13254269e-01,
         7.50241687e-01,  5.22512440e-01,  4.59613793e-02,
        -5.72801649e-01],
       [-2.10739473e-01, -1.64729163e+00, -6.54689306e-01,
        -2.46736970e+00, -2.18771745e+00,  5.51709988e-02,
        -1.22714670e+00, -3.04959714e+00, -2.94815912e-01,
        -1.

In [59]:
s[1][4]

-0.5836070349294393

In [61]:
s[1]

array([ 8.02585426e-01, -1.35283220e+00,  6.99936356e-01,  2.11413109e+00,
       -5.83607035e-01, -7.11109924e-01,  4.33078323e-01, -8.64582927e-01,
        1.48840956e-04, -2.49997164e+00])

In [62]:
s[1:10:2]

array([[ 8.02585426e-01, -1.35283220e+00,  6.99936356e-01,
         2.11413109e+00, -5.83607035e-01, -7.11109924e-01,
         4.33078323e-01, -8.64582927e-01,  1.48840956e-04,
        -2.49997164e+00],
       [ 5.15948230e-01, -1.78815028e+00,  1.11027204e+00,
        -2.02900696e+00,  1.94846028e+00, -6.13254269e-01,
         7.50241687e-01,  5.22512440e-01,  4.59613793e-02,
        -5.72801649e-01],
       [ 1.54421840e+00, -1.12957610e-01, -1.37449786e+00,
        -7.61797071e-01, -4.60217617e-01, -1.99526622e+00,
         4.40237129e-01, -1.18366968e+00, -9.20025278e-01,
        -4.29328388e-01],
       [-7.02468300e-01, -1.06657248e-01,  6.48885167e-01,
        -2.45573290e-01, -1.78232333e+00,  1.06278504e+00,
        -2.02396561e+00,  2.06112051e+00, -2.47504058e-01,
         8.30720893e-01],
       [ 1.55990041e-01, -5.16380511e-01,  3.97543023e-02,
         4.31682829e-01, -2.13962683e-01,  5.75588975e-01,
        -4.46258247e-01,  7.77042017e-01, -4.31945302e-01,
        -1.

In [85]:
t = np.ones((5,5))

In [86]:
t

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
t[1:-1,1:-1] = 0

In [84]:
t

array([[1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [90]:
t[1:4,2:4] = 0

In [91]:
t

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

t[1:4,2:4] = 0

In [94]:
t[1:4,2:4] = 5

In [95]:
t

array([[1., 1., 1., 1., 1.],
       [1., 0., 5., 5., 1.],
       [1., 0., 5., 5., 1.],
       [1., 0., 5., 5., 1.],
       [1., 1., 1., 1., 1.]])

In [2]:
x = np.random.randn(3,2)

In [3]:
y = np.random.randn(2,3)

In [4]:
x.dot(y)

array([[-0.71526435, -1.0135794 ,  1.88523509],
       [-2.97735182, -2.2814238 ,  4.77900452],
       [-1.72235887, -0.78113544,  1.91162392]])

In [6]:
x.transpose() # 3 by 2 ka martix 2 by 3 ma convert ho gaya

array([[ 1.0441702 ,  0.47543884, -0.80102679],
       [ 0.18697173,  1.59154704,  1.1467587 ]])

In [7]:
x.trace()

2.635717233514753

In [8]:
# jub be hum machine learnong par kaam karty han tu huma data kii bise nes khtm karnay kae liya randonly data genrate karna hota han

In [15]:
np.random.normal(size=(3,3))

array([[-0.38989119,  1.90778163,  1.83299467],
       [ 0.76641194,  1.23006194,  1.01365963],
       [ 1.72035759,  0.23467499, -0.92752224]])

In [18]:
np.random.uniform(size=(3,4))

array([[0.11406533, 0.27999987, 0.61992026, 0.21906784],
       [0.9802927 , 0.65437785, 0.36349527, 0.45511942],
       [0.57935531, 0.36934461, 0.9656798 , 0.9517539 ]])

# Numpy Advances Array Manipulation

# Reshape

In [21]:
x = np.random.randn(4,5)

In [22]:
x

array([[ 0.53866319, -1.55353416,  0.10309869,  2.18050789,  1.25743076],
       [ 1.0417212 ,  1.07288052, -0.48288338,  0.6435315 ,  1.18496351],
       [-1.57881695,  0.81244275,  0.35746243, -0.42384212, -0.2103324 ],
       [-0.26263973,  0.17047128, -1.0049597 ,  0.89536735, -0.09857476]])

In [23]:
x.reshape(2,2,5)

array([[[ 0.53866319, -1.55353416,  0.10309869,  2.18050789,
          1.25743076],
        [ 1.0417212 ,  1.07288052, -0.48288338,  0.6435315 ,
          1.18496351]],

       [[-1.57881695,  0.81244275,  0.35746243, -0.42384212,
         -0.2103324 ],
        [-0.26263973,  0.17047128, -1.0049597 ,  0.89536735,
         -0.09857476]]])

In [24]:
x.reshape(2,2,-1)

array([[[ 0.53866319, -1.55353416,  0.10309869,  2.18050789,
          1.25743076],
        [ 1.0417212 ,  1.07288052, -0.48288338,  0.6435315 ,
          1.18496351]],

       [[-1.57881695,  0.81244275,  0.35746243, -0.42384212,
         -0.2103324 ],
        [-0.26263973,  0.17047128, -1.0049597 ,  0.89536735,
         -0.09857476]]])

In [26]:
x.ravel() # array one dimension ma convert ho jatiii han

array([ 0.53866319, -1.55353416,  0.10309869,  2.18050789,  1.25743076,
        1.0417212 ,  1.07288052, -0.48288338,  0.6435315 ,  1.18496351,
       -1.57881695,  0.81244275,  0.35746243, -0.42384212, -0.2103324 ,
       -0.26263973,  0.17047128, -1.0049597 ,  0.89536735, -0.09857476])

# Concatenate

In [28]:
x = [[1,3,5,6],[7,8,9,4]]

In [29]:
arr1 = np.array(x)

In [30]:
arr1

array([[1, 3, 5, 6],
       [7, 8, 9, 4]])

In [31]:
y = [[11,13,15,19],[17,19,15,16]]

In [32]:
arry = np.array(y)

In [33]:
arry

array([[11, 13, 15, 19],
       [17, 19, 15, 16]])

In [35]:
np.concatenate((arr1,arry),axis=0) # row vise concatente ho raha han

array([[ 1,  3,  5,  6],
       [ 7,  8,  9,  4],
       [11, 13, 15, 19],
       [17, 19, 15, 16]])

In [36]:
np.concatenate((arr1,arry),axis=1)

array([[ 1,  3,  5,  6, 11, 13, 15, 19],
       [ 7,  8,  9,  4, 17, 19, 15, 16]])

# Split

In [2]:
x = [1,2,3,4,5,6,7,8,9,10]

In [3]:
d = np.array(x)

In [4]:
np.split(d,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10])]

In [5]:
x = [[10,20,30,40,50],[60,70,80,90,100]]

In [6]:
s = np.array(x)

In [9]:
np.split(s,[4,2])

[array([[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]]),
 array([], shape=(0, 5), dtype=int32),
 array([], shape=(0, 5), dtype=int32)]

# Tilte And Report

In [10]:
d = np.array([1,5,7,8,9])

In [11]:
np.repeat(d,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8, 9, 9, 9])

In [12]:
np.tile(d,2)

array([1, 5, 7, 8, 9, 1, 5, 7, 8, 9])